apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  labels:
    app: automl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automl
  template:
    metadata:
      labels:
        app: automl
    spec:
      containers:
      - name: automl
        image: zhaoyunpeng/automl-hello-go:v1
        ports:
        - containerPort: 9000